#pragma once

#include <map>
#include <string>
#include <vector>

namespace hwinfo::unix_os::cpu {

struct CPU {
  struct Core {
    std::uint64_t id = 0;
    std::array<std::uint64_t, 4> cache_bytes = {0, 0, 0, 0};
    std::uint64_t regular_frequency_hz = 0;
    std::uint64_t max_frequency_hz = 0;
    bool smt = false;
    std::vector<std::string> flags;
  };
  std::uint32_t socket_id;
  std::string model;
  std::string vendor;
  std::map<std::uint32_t, Core> cores;
};

/**
 * parses the provided /proc/cpuinfo file conenten into a map <socket_id, <core_id, <key, value>>>
 */
std::map<std::uint32_t, std::map<std::uint32_t, std::map<std::string, std::string>>> parse_cpuinfo_file(
    const std::string& data);

/**
 * parses a sockets map (generated by e.g. parse_cpuinfo_file) into a vector of CPU instances
 */
std::map<std::uint32_t, unix_os::cpu::CPU> parse_cpus(
    const std::map<std::uint32_t, std::map<std::uint32_t, std::map<std::string, std::string>>>& sockets);

}  // namespace hwinfo::unix_os::cpu